---
version: '2'
services:
  zookeeper1:
    image: confluentinc/cp-zookeeper:5.5.1
    hostname: zookeeper1
    container_name: zookeeper1
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  zookeeper2:
    image: confluentinc/cp-zookeeper:5.5.1
    hostname: zookeeper2
    container_name: zookeeper2
    ports:
      - "2182:2182"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2182
      ZOOKEEPER_TICK_TIME: 2000

  zookeeper3:
    image: confluentinc/cp-zookeeper:5.5.1
    hostname: zookeeper3
    container_name: zookeeper3
    ports:
      - "2183:2183"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2183
      ZOOKEEPER_TICK_TIME: 2000


  broker1:
    image: confluentinc/cp-kafka:5.5.1
    hostname: broker1
    container_name: broker1
    depends_on:
      - zookeeper1
    ports:
      - "29091:29091"
      - "9091:9091"
      - "9101:9101"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper1:2181'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://broker1:29091,PLAINTEXT_HOST://localhost:9091
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_JMX_PORT: 9101
      KAFKA_NUM_PARTITIONS: 10

  broker2:
    image: confluentinc/cp-kafka:5.5.1
    hostname: broker2
    container_name: broker2
    depends_on:
      - zookeeper2
    ports:
      - "29092:29092"
      - "9092:9092"
      - "9102:9102"
    environment:
      KAFKA_BROKER_ID: 2
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper2:2182'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://broker2:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_JMX_PORT: 9102
      KAFKA_NUM_PARTITIONS: 10

  broker3:
    image: confluentinc/cp-kafka:5.5.1
    hostname: broker3
    container_name: broker3
    depends_on:
      - zookeeper3
    ports:
      - "29093:29093"
      - "9093:9093"
      - "9103:9103"
    environment:
      KAFKA_BROKER_ID: 2
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper3:2183'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://broker3:29093,PLAINTEXT_HOST://localhost:9093
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_JMX_PORT: 9103
      KAFKA_NUM_PARTITIONS: 10

  rest-proxy1:
    image: confluentinc/cp-kafka-rest:5.5.1
    depends_on:
      - zookeeper1
      - broker1
    ports:
      - 8081:8081
    hostname: rest-proxy1
    container_name: rest-proxy1
    environment:
      KAFKA_REST_HOST_NAME: rest-proxy1
      KAFKA_REST_BOOTSTRAP_SERVERS: 'broker1:29091'
      KAFKA_REST_LISTENERS: "http://0.0.0.0:8081"

  rest-proxy2:
    image: confluentinc/cp-kafka-rest:5.5.1
    depends_on:
      - zookeeper2
      - broker2
    ports:
      - 8082:8082
    hostname: rest-proxy2
    container_name: rest-proxy2
    environment:
      KAFKA_REST_HOST_NAME: rest-proxy2
      KAFKA_REST_BOOTSTRAP_SERVERS: 'broker2:29092'
      KAFKA_REST_LISTENERS: "http://0.0.0.0:8082"

  rest-proxy3:
    image: confluentinc/cp-kafka-rest:5.5.1
    depends_on:
      - zookeeper3
      - broker3
    ports:
      - 8083:8083
    hostname: rest-proxy3
    container_name: rest-proxy3
    environment:
      KAFKA_REST_HOST_NAME: rest-proxy3
      KAFKA_REST_BOOTSTRAP_SERVERS: 'broker3:29093'
      KAFKA_REST_LISTENERS: "http://0.0.0.0:8083"

  control-center:
    image: confluentinc/cp-enterprise-control-center:5.5.1
    hostname: control-center
    container_name: control-center
    depends_on:
      - zookeeper1
      - broker1
    ports:
      - "9021:9021"
    environment:
      CONTROL_CENTER_BOOTSTRAP_SERVERS: 'broker1:29091'
      CONTROL_CENTER_ZOOKEEPER_CONNECT: 'zookeeper1:2181'
      CONTROL_CENTER_REPLICATION_FACTOR: 1
      CONTROL_CENTER_INTERNAL_TOPICS_PARTITIONS: 1
      CONTROL_CENTER_MONITORING_INTERCEPTOR_TOPIC_PARTITIONS: 1
      CONFLUENT_METRICS_TOPIC_REPLICATION: 1
      PORT: 9021

  mirror-maker:
    build: ./mirror-maker-docker/
    depends_on:
      - broker1
      - broker2
      - broker3
    hostname: mirror-maker
    container_name: mirror-maker
